INSERT INTO contributors(name, created_at, updated_at) VALUES('William Wright', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Greg Daniels', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Edgar Allan Poe', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Carlos Baeza', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Tim Long', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Neil Affleck', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Steve O''Donnell', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Chambers', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Sam O''Neal', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mike Reiss', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Patric M. Verrone', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Chuck Sheetz', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('John Swartzwelder', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('(David Silverman)', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Marc Wilmore', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bill Oakley', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Steve Tompkins', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matt Selman', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Richard Appel', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Rachel Pulido', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Neil Boushall', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jon Vitti', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Stephanie Gillis', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dennis Snee', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Milton Gray', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Lance Kramer', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Don Payne (with John Frink)', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dan Castellaneta', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Spike Feresten', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ricky Gervais (who also guest stars)', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David S. Cohen', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David X. Cohen', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jeff Westbrook', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bob Anderson', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matthew Faughnan', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Valentina L. Garza', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Julie Thacker', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Howard Gewirtz', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brian K. Roberts', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Rob LaZebnik', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brad Bird', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Story: Bob Kushell', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Don Payne', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Daniel Chun', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ken Levine', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Alan Smart', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Larry Doyle', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Lauren MacMullan', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Wes Archer', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jeffrey Ventimilia', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Adam I. Lapidus', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Marc Wilmore (as "Marc Will Killmore")', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Frank Mula', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mark Ervin', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ned Goldreyer', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Raymond S. Persi', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jace Richdale', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Tom Martin', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brian Scully', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Chris Clements', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Teleplay: John Swartzwelder', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Michael Nobori', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jay Kogen', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('John Frink (with Don Payne)', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Sacks', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Nancy Kruse', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Steven Dean Moore', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Evan Goldberg', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Michael Carrington', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Pound Foolish', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Donick Cary', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matthew C. Faughnan', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Michael Price', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dominic Polcino', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matt Marshall', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bill Freiberger', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Robert Cohen', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Richardson', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bob Kushell', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Chris Cluess', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Conan O''Brien', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('(Jon Vitti)', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Isaacs', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David M. Stern', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Michael Marcantel', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jennifer Crittenden', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matthew Nastuk', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Shaun Cashman', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Joel H. Cohen', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Deb Lacusta', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Robin J. Stein', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Steve Pepoon', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Al Jean', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mark Kirkland', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bill Canterbury', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('J. Stewart Burns', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Gregg Vanzo', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Swinton O. Scott III', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Allen Glazier', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brent Forrester', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dana Gould', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Steve Viksten', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Reid Harrison', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Lawrence Talbot', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Teleplay: Jon Vitti', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Peter Gaffney', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Klay Hall', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ron Hauge', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Andrew Kreisberg', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mick Kelly', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Nell Scovell', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Billy Kimball', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Mirkin', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Teleplay: Joshua Sternin', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matthew Schofield', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Carolyn Omine', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Sam Simon', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bob Bendetson', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mert Rich', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Wesley Archer', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matt Groening', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Michael Polcino', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jeffrey Lynch', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jen Kamerman', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Story: Al Jean', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Joshua Sternin', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jane O''Brien', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Story: Sam Simon', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jeff Martin', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Thomas Chastain', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dan McGrath', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brian Pollack', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mike B. Anderson', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jack Barth', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Rob Oliver', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('(credited as "Penny Wise")', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mimi Pond', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('George Meyer', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Bill Odenkirk', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ken Keeler', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ian Maxtone-Graham', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Rich Moore', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Susie Dietter', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Josh Weinstein', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Pete Michels', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Kent Butterworth', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jonathan Collier', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Kevin Curran', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Gary Apple', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Jim Reardon', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mitchell H. Glazer', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Josh Lieb', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dan Greaney', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brendan Hay', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Dick Blasucci', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Penny Wise', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Mike Scully', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Steve Young', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Silverman', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Matt Warburton', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('John Frink', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Ralph Sosa', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Brian Kelley', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Seth Rogen', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Wallace Wolodarsky', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('Julie Chambers', datetime('now'), datetime('now'));
INSERT INTO contributors(name, created_at, updated_at) VALUES('David Silverman (as "Godzilla vs. Silverman")', datetime('now'), datetime('now'));
